### ISSUE TITLE
No module named sphinxjp.themes.impressjs

### ISSUE THREAD

**Issue by dorneanu** [shkumagai/sphinxjp.themes.impressjs#3]
Hi,

following your instructions to build the slides using sphinx and impress I get:

```
blackarch :: impress/sphinx » make html
sphinx-build2 -b html -d build/doctrees   source build/html
Running Sphinx v1.4.3

Extension error:
Could not import extension sphinxjp.themes.impressjs (exception: No module named sphinxjp.themes.impressjs)
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 1

```

And yes, `sphinxjp.themes.impressjs` is already installed. Any ideas?

**Comment by gnyers** [comment]
Had the same error, turned out that I've installed sphinxjp.themes.impressjs for the wrong version of python. In my case, I've installed it for Python2, while Sphinx uses Python3. 

Be explicit when installing, use either pip2 or pip3. If still doesn't work, use 'python -m pip install ...' (Python2) or 'python3 -m pip install ...' (Python3)
